[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.file]
    directory = "/etc/traefik/dynamic/"
    watch = true
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

[certificatesResolvers]
  [certificatesResolvers.le.acme]
    email = "your-email@example.com"
    storage = "acme.json"
    [certificatesResolvers.le.acme.httpChallenge]
      entryPoint = "web"

[log]
  level = "INFO"

[accessLog]

[api]
  dashboard = true
  insecure = true

[ping]

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"
